spring:
  datasource:
    url: jdbc:mysql://localhost:43306/vega?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lyz950725
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true